### ISSUE TITLE
Errors with RDFlib 6.0 from integrated JSON-LD plugin

### ISSUE THREAD

**Issue by pattersoniv** [jupyrdf/ipyradiant#119]
rdflib [6.0 has integrated the JSON-LD plugin](https://rdflib.readthedocs.io/en/stable/upgrade5to6.html?highlight=json-ld#json-ld-integration-and-json-ld-1-1) into the core library.  They have loaded their [SUFFIX_FORMAT_MAP with related JSON-LD](https://github.com/RDFLib/rdflib/blob/master/rdflib/util.py#L369) terms. This causes an error when defining the new [SUFFIX_FORMAT_MAP locally](https://github.com/jupyrdf/ipyradiant/blob/master/src/ipyradiant/loader/util.py#L11), as it doubles up kwargs. 

A rdflib pin would be a quickfix, or removing the JSON-LD plugin utilities would be better long term.

**Comment by zwelz3** [comment]
Closed by #121
