### ISSUE TITLE
Need fixture data for examples and future tests

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyradiant#18]
Need a basic example ttl file that we can use in the notebook examples and future tests. This can be replaced with a better process/example later, but we need something in the short-term.

**Comment by zwelz3** [comment]
Maybe requesting one from e.g. schema.org is enough for testing.

**Comment by nrbgt** [comment]
#32 and #33 are running very slowly on windows: I think we'll indeed want a different, smaller set of fixtures for (at least) windows...

**Comment by zwelz3** [comment]
Closing thanks to Nicks work on https://github.com/jupyrdf/ipyradiant/pull/36
