### ISSUE TITLE
Add index page for notebook examples

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyradiant#21]
For now, will use normal notebook hyperlinks to develop an index landing page that categorizes examples. 
In the future, may want to move to something more like [Jupyter{book}](https://jupyterbook.org/intro.html).

**Comment by nrbgt** [comment]
Yeah, the static site publishing target is good goal, but it takes some work to make kernel-less linked visualizations work: a lot of stuff would have to be made to work with `ipywidgets.jslink`.

Another intermediate approach:

https://github.com/deathbeds/wxyz/blob/master/notebooks/index.ipynb

This uses `importnb` to treat the landing page load up all the demo applications. By importing the other example notebooks:
- your "landing page" can put the best content up front (ideally just one a one-line code cell to import and show each example) 
- imported notebooks need to stay in a "restart-run-all"-able state... this is a blessing and a curse, as the index will serve as a good smoke test before running "heavy" notebooks
- eventually, this helps move towards packaged notebooks, to make finding things more convenient.
