### ISSUE TITLE
Linked Multi Select Widget

### ISSUE THREAD

**Issue by lnijhawan** [jupyrdf/ipyradiant#25]
A linked multi select widget that can be used to down-select predicates that a user wishes to collapse.

**Comment by zwelz3** [comment]
In general, I think the need for a clean widget that allows a user to multi-select while easily seeing what things have been "added" to the selected "group" is necessary (especially with graphs where there may be hundreds of options. 

The widget class should also allow you to supply a set (upon init or as an attribute update) that it attempts to automatically add all things in the set to the "added" widget box.
