### ISSUE TITLE
🌞 Release 0.1.1 (J_e_v) 📦

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyradiant#45]
Blockers:
- [x] #44: networkx version pin, lazy loading
- [x] review changelog
- [x] validate on binder
- [x] tag
- [x] pip release 
- [x] conda release
  - [x] update version pins

Follow-on:
- [x] bump version
- [x] resolve envs

**Comment by zwelz3** [comment]
https://github.com/jupyrdf/ipyradiant/releases/tag/v0.1.1
