### ISSUE TITLE
🌞 Release 0.1.2 J_e 📦

### ISSUE THREAD

**Issue by zwelz3** [jupyrdf/ipyradiant#69]
Incremental improvements over 0.1.1

Blockers:
* [x] #50 
* [x] #55 
* [x] #61 
* [x] #68
* [x] #74
* [x] cleanup PR
* [x] Binder
  * [x] Cytoscape not showing in Binder?
* [x] Docs
  * [x] Review changelog
  * [x] Review README
     * [x] Update screencasts in README?
* [x] Release
  * [x] tag, upload CI-built assets with checksum
  * [x] pypi
* [x] [Post-mortem ](https://github.com/jupyrdf/ipyradiant/pull/89)
  * [x] bump version to 0.1.3
  * [x] conda-forge
  * [x] Update release procedure

**Comment by nrbgt** [comment]
- note for postmortem
  - dist is too big, take out the smoke test html
  - [calculate SHA256SUMs](https://github.com/jupyrdf/ipyelk/blob/master/dodo.py#L285-L304)

**Comment by zwelz3** [comment]
Completed
