### ISSUE TITLE
Update Deprecated API in starwars.ttl from examples/

### ISSUE THREAD

**Issue by RhythmSyed** [jupyrdf/ipyradiant#71]
The starwars data source API https://swapi.co/ is deprecated and needs to be updated to https://swapi.dev.

The API is also invoked differently:

For a resource like this: **https://swapi.co/resource/human/11**
Now has to be called like this: **https://swapi.dev/api/people/11**
This is referencing **Anakin Skywalker**

The file is here: https://github.com/jupyrdf/ipyradiant/blob/master/examples/data/starwars.ttl

**Comment by zwelz3** [comment]
New swapi only hosts the data as JSON (without the means to recover the context). 
Tracking issue [here](https://github.com/Juriy/swapi/issues/26).

**Comment by zwelz3** [comment]
No traction on the tracking issue. We will assume that the new starwars dataset will not include JSON-LD, and therefore will keep this old version of the starwars data until a suitable example dataset is identified.
