### ISSUE TITLE
Support JupyterLab 3

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyradiant#72]
It's worth a look to see which (if any) of the upstreams haven't been released to support lab3. Going to 3 would remove node/npm entirely from this repo for everything except `prettier`, which we can vendor, and would improve both development time and potentially CI.

## real dependencies

| extension      | status | link |
|----------------|--------|------|
| @jupyter-widgets/jupyterlab-manager | ready | https://pypi.org/project/jupyterlab-widgets/1.0.0/
| @pyviz/jupyterlab_pyviz | ready | https://pypi.org/project/pyviz-comms/2.0.1/
| jupyter-cytoscape | ready | https://pypi.org/project/ipycytoscape/1.2.0/
| qgrid2 | dead | ---

### what to do about qgrid
- alternatives
    - [ipyregulartable](https://github.com/jpmorganchase/ipyregulartable)
        - support merged, probably releasing _real soon now_
    - [wxyz-datagrid](https://github.com/deathbeds/wxyz/issues/42)
        - not started yet

## dev/docs dependencies
| extension      | status | link |
|----------------|--------|------|
| @deathbeds/jupyterlab-drawio-notebook@0.8.0-alpha1 | not started | https://github.com/deathbeds/jupyterlab-drawio/issues/11
| @deathbeds/jupyterlab-drawio-webpack@13.6.2-alpha1 | not started | https://github.com/deathbeds/jupyterlab-drawio/issues/11
| @deathbeds/jupyterlab-drawio@0.8.0-alpha1 | not started | https://github.com/deathbeds/jupyterlab-drawio/issues/11

**Comment by zwelz3** [comment]
Is this closed by #69 ? I know we added JL3 in the README, but I'm not sure if that means everything is properly supported.

**Comment by zwelz3** [comment]
After speaking with @sanbales we are going to bump ipyradiant to JL3 and pin cytoscape >=1.2.0. 

qgrid is no longer a hard dependency (although some mentions still exist in README), so we shouldn't have any issue with upstreams.
